### ISSUE TITLE
Download additional taxonomic info in swissprot data

### ISSUE THREAD

**Issue by rcxwhiz** [RyloByte/TS-Capstone-2025#12]
Moved from old repository: [#44](https://github.berkeley.edu/Chem-283/Tbio-UBC-1/issues/44)

---

Right now taxonomic IDs are downloaded, should add the human readable lineage to it

---

These are specified in the url query string in the rule for downloading the database.

---

Touched on during the sponsor meeting today. Floating.

**Comment by rcxwhiz** [comment]
If any of the downloads that go into `utils/` are updated, the script for running tests on GitHub actions will also need to be updated. The `key` in the `cache utils` step will need to be changed:

```yaml
  - name: cache utils
    id: cache-utils
    uses: actions/cache@v4
    with:
      path: |
        ./hyperpackage_snakemake/utils
      key: fixed-key  <-- change this to make actions redownload databases
```

Another thing that could be done to take care of multiple things is to change the name of the downloaded file, ex. to `utils/swissprot_data_v2.tar.gz`, and then update the name of that file in all the rules that require it in the `Snakefile`. This will trigger the github actions script and all users to redownload the file. This would probably actually be the best strategy to go with because it will automatically make the users download the new, correct version, and indicate to them what version of the downloaded database they're on.
