### ISSUE TITLE
Rethink automated testing

### ISSUE THREAD

**Issue by rcxwhiz** [RyloByte/TS-Capstone-2025#34]
It's becoming clear that the way we're doing the automated testing for this repo is not feasible when it takes possibly over 30 mins to run when there's a cache miss. 

There are a few avenues we can take with this, but the automated tests are useless at this point.

**Comment by rcxwhiz** [comment]
Just checked and this morning it looks like the swissprot db file could take over 4 hours to download, which is much longer than usual, but would explain the issues with the testing last night.

**Comment by rcxwhiz** [comment]
I tried committing the utils files to a forked repository and it went fine. At this point I think we need to do that even for the user because it looks like the uniprot APIs we rely on are unstable. 

On that forked repository the tests are still timing out with a code 143, and I don't know why. As far as I know github actions and pytest should not timeout, but it's ending after about 5 minutes of the pytest step. 

It would appear at this point that some of the clustering tests can be pretty lengthy. As part of a potential automated regression test suite we might have to only include smaller clustering tests, although there aren't *supposed* to be problems with timeouts. 

One thing that should probably be done is using mamba instead of conda in the actions scripts:

```yaml
- name: Install Mamba
  run: conda install -n base -c conda-forge mamba
- name: Create env
  run: mamba env create -f environment.yaml
```

and caching the environments, including the ones in `workflow/envs`

```yaml
- name: Set up Miniconda
  uses: conda-incubator/setup-miniconda@v2
  with:
    activate-environment: myenv
    environment-file: environment.yaml
    python-version: "3.9"  # Optional: Pin Python version

- name: Get Conda environment cache key
  id: cache-key
  run: |
    echo "key=$(sha256sum environment.yaml | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

- name: Cache Conda environment
  uses: actions/cache@v3
  id: conda-cache
  with:
    path: |
      ~/conda_pkgs_dir
      $CONDA/envs/myenv
    key: conda-${{ steps.cache-key.outputs.key }}

- name: Install dependencies (if cache miss)
  if: steps.conda-cache.outputs.cache-hit != 'true'
  run: |
    conda env update -n myenv -f environment.yaml
    conda clean -afy  # Clean unused packages
```

As long as there's no billing problem with the repository it theoretically shouldn't be a problem to have the tests run long and potentially provide real value.
